# Generated by Django 4.0.1 on 2022-01-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_firstName', models.CharField(max_length=25)),
                ('customer_lastName', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('customer_password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'butta_customer',
            },
        ),
    ]
